services:
  db:
    image: postgres:15
    container_name: productos_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=productos_db
    ports:
      - "5434:5432"       # Host 5434 -> Contenedor 5432
    volumes:
      - productos_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  inventario-ms:
    build:
      context: ..         # Ruta al proyecto (donde estÃ¡ el pom.xml)
    container_name: inventario_ms
    ports:
      - "8090:8090"       # Host 8090 -> Contenedor 8090
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=productos_db
      - DB_USER=admin
      - DB_PASSWORD=admin123

      - API_KEY=super-secret-key
      - OUTBOUND_API_KEY=super-secret-key
      - SERVER_PORT_INV=8090
      - SPRING_PROFILES_ACTIVE=prod
      - UPLOAD_DIR=/uploads
    depends_on:
      - db
    volumes:
      - ./uploads:/uploads

volumes:
  productos_data:
