server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    compatibility-verifier:
      enabled: false


security:
  api-key: ${API_KEY:super-secret-key}
  outbound-api-key: ${OUTBOUND_API_KEY:super-secret-key}

clients:
  productos:
    # Para desarrollo local (producto-ms en localhost)
    # base-url: http://localhost:8080/producto-ms/api/productos
    # si luego ambos est√°n en Docker en la misma red:
    base-url: http://producto-ms:8080/producto-ms/api/productos

springdoc:
  api-docs:
    path: /inventario-sm/v3/api-docs
  swagger-ui:
    path: /inventario-sm/swagger-ui

app:
  swagger:
    title: Inventario MS
    description: El microservicio Inventario MS se encarga de gestionar existencias y validar productos contra el microservicio de productos.
    version: 1.0.0
